### ISSUE TITLE
cancel execution of a command if it fails on one host

### ISSUE THREAD

**Issue by jessicatoscani** [exoscale/zlocker#6]
It could be very useful to have a way to stop the execution of a command on hosts after it fails on one host.

- don't release lock if command fails
- add an execution timeout so if a host can't get a lock after thus duration, execution is cancelled

**Comment by greut** [comment]
The way a [Lock](https://github.com/samuel/go-zookeeper/blob/master/zk/lock.go#L42-L136) is implemented makes it hard to hold to it, while being able to retake it later on. An easier algorithm could be to impose a sequence of execution.

**Comment by pyr** [comment]
I think this is an orchestrator concern, not agent concern. Things should thus be handled at the orchestrator level (warp).
